const LIGHT_GREEN = '#03C988'
const CREAM = '#FFF6EA'
const LIGHT_BLUE = '#54A7FF'
const GREY = '#D0D0D0'
const BLACK = '#282828'
const RED = '#F34E4E'
const DARK_YELLOW = '#FFCC00'
const WHITE = '#FFFFFF'

const COLORS = {
    PRIMARY: LIGHT_GREEN,
    SEONDARY: CREAM,
    ACTION: LIGHT_BLUE,
    ERROR: RED,
    WARNING: DARK_YELLOW,
    GREY: GREY,
    BLACK: BLACK,
    WHITE: WHITE,
}

export default COLORS
